spring:
  application:
    name: recipe-api

  datasource:
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    contexts: prod

logging:
  level:
    liquibase: INFO
    org.springframework.boot.autoconfigure.liquibase: DEBUG

