spring:
  application:
    name: recipe-api

  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB}
    username: ${APP_USER}
    password: ${APP_PASSWORD}
    driver-class-name: org.postgresql.Driver

    hikari:
      pool-name: rw-pool
